import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ArchiveBoxIcon } from '@heroicons/react/24/outline';
import servicesData from '../data/services.data';
export default function HomePage() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</div>
	);
}
